export const MUSIC_TRACKS = [
  {
    id: 'xenovoya-title-menu',
    src: '/audio/music/xenovoya-title-menu.mp3',
    title: 'Title Menu',
    state: 'Title',
    trigger: 'home / public shell / no active run',
    desc: 'Slow analog beacon, star-chart ambience, and distant metallic bells.',
    duration: 45,
    durationLabel: '45.0s',
    volume: 0.32,
  },
  {
    id: 'xenovoya-lobby-setup',
    src: '/audio/music/xenovoya-lobby-setup.mp3',
    title: 'Lobby Setup',
    state: 'Lobby',
    trigger: 'game lobby / waiting for crew / setup screens',
    desc: 'Quiet hangar room tone, equipment pulses, and patient preparation groove.',
    duration: 45,
    durationLabel: '45.0s',
    volume: 0.32,
  },
  {
    id: 'xenovoya-expedition-calm',
    src: '/audio/music/xenovoya-expedition-calm.mp3',
    title: 'Expedition Calm',
    state: 'Expedition Calm',
    trigger: 'active game / low-risk planning',
    desc: 'Dusty modular arpeggios, soft metallic percussion, and compass motif.',
    duration: 60,
    durationLabel: '60.0s',
    volume: 0.34,
  },
  {
    id: 'xenovoya-expedition-danger',
    src: '/audio/music/xenovoya-expedition-danger.mp3',
    title: 'Expedition Danger',
    state: 'Danger',
    trigger: 'high risk / invalid route pressure / redline moments',
    desc: 'Tense modular bass, urgent muted toms, warning harmonics, and survival pressure.',
    duration: 60,
    durationLabel: '60.0s',
    volume: 0.34,
  },
  {
    id: 'xenovoya-camp-recovery',
    src: '/audio/music/xenovoya-camp-recovery.mp3',
    title: 'Camp Recovery',
    state: 'Camp / Recovery',
    trigger: 'camp, rest, recovery, post-resolution breather',
    desc: 'Firelike synth crackle, filtered pads, gentle percussion, and fragile safety.',
    duration: 45,
    durationLabel: '45.0s',
    volume: 0.32,
  },
  {
    id: 'xenovoya-relic-discovery',
    src: '/audio/music/xenovoya-relic-discovery.mp3',
    title: 'Relic Discovery',
    state: 'Relic Discovery',
    trigger: 'dig / artifact found / rare beat',
    desc: 'Shimmering glass harmonics, tuned percussion, magnetic drone, and unease.',
    duration: 45,
    durationLabel: '45.0s',
    volume: 0.34,
  },
  {
    id: 'xenovoya-chain-resolving',
    src: '/audio/music/xenovoya-chain-resolving.mp3',
    title: 'Chain Resolving',
    state: 'Resolving',
    trigger: 'transaction pending / chain resolving / waiting on outcome',
    desc: 'Ticking data pulses, low sequenced synth, granular delay, and suspense.',
    duration: 45,
    durationLabel: '45.0s',
    volume: 0.31,
  },
  {
    id: 'xenovoya-victory-extraction',
    src: '/audio/music/xenovoya-victory-extraction.mp3',
    title: 'Victory Extraction',
    state: 'Victory',
    trigger: 'game over won / extraction success',
    desc: 'Bright analog brass pads, compass arpeggio, and warm major-key release.',
    duration: 45,
    durationLabel: '45.0s',
    volume: 0.34,
  },
  {
    id: 'xenovoya-defeat-lost',
    src: '/audio/music/xenovoya-defeat-lost.mp3',
    title: 'Defeat Lost',
    state: 'Defeat',
    trigger: 'game over lost / failed extraction',
    desc: 'Detuned synth elegy, broken beacon, low percussion, and distant storm noise.',
    duration: 45,
    durationLabel: '45.0s',
    volume: 0.33,
  },
  {
    id: 'xenovoya-expedition-loop',
    src: '/audio/music/xenovoya-expedition-loop.mp3',
    title: 'Expedition Loop',
    state: 'Expedition Alt',
    trigger: 'manual audition / alternate exploration bed',
    desc: 'Original ACE-Step expedition loop with analog pulse and glass harmonics.',
    duration: 60,
    durationLabel: '60.0s',
    volume: 0.34,
  },
];

export const MUSIC_TRACK_BY_ID = Object.fromEntries(
  MUSIC_TRACKS.map((track) => [track.id, track]),
);

export const DEFAULT_MUSIC_TRACK_ID = 'xenovoya-title-menu';

export const GAME_MUSIC = MUSIC_TRACK_BY_ID[DEFAULT_MUSIC_TRACK_ID];

export const FEEDBACK_AUDIO = {
  invalid: { src: '/audio/sfx/invalid.wav', volume: 0.42 },
  commit: { src: '/audio/sfx/commit.wav', volume: 0.38 },
  rush: { src: '/audio/sfx/rush.wav', volume: 0.3 },
  move: { src: '/audio/sfx/move.wav', volume: 0.24 },
  'tx-pending': { src: '/audio/sfx/tx-pending.wav', volume: 0.24 },
  'tx-confirming': { src: '/audio/sfx/tx-confirming.wav', volume: 0.22 },
  'tx-success': { src: '/audio/sfx/tx-success.wav', volume: 0.34 },
  'tx-error': { src: '/audio/sfx/tx-error.wav', volume: 0.34 },
};

export const FEEDBACK_FALLBACK = {
  invalid: { frequency: 120, type: 'square', gain: 0.024, vibrate: 34 },
  commit: { frequency: 420, type: 'triangle', gain: 0.014, vibrate: 18 },
  rush: { frequency: 330, type: 'triangle', gain: 0.016, vibrate: 12 },
  move: { frequency: 260, type: 'triangle', gain: 0.012, vibrate: 8 },
  'tx-pending': { frequency: 180, type: 'sine', gain: 0.01, vibrate: 6 },
  'tx-confirming': { frequency: 240, type: 'sine', gain: 0.01, vibrate: 6 },
  'tx-success': { frequency: 520, type: 'triangle', gain: 0.016, vibrate: 18 },
  'tx-error': { frequency: 100, type: 'square', gain: 0.02, vibrate: 30 },
};
